; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_upload.flash_size = 4MB
board_build.flash_size = 4MB
board_build.partitions = partitions.csv
board_build.filesystem = littlefs

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM

build_src_filter =
    +<*>
    -<motor_test_main.cpp>

lib_deps =
    moononournation/GFX Library for Arduino@1.5.9
    adafruit/Adafruit GFX Library@1.11.11
    bblanchon/ArduinoJson@7.4.2

[env:motor-test]
extends = env:esp32-s3-devkitm-1
build_src_filter =
    -<*>
    +<motor_test_main.cpp>
    +<drivers/MotorDriver.cpp>
